print('Opening supplied cursor')
local sprite = app.open(app.params.input)
assert(sprite and #sprite.frames == 1, 'Expected one cursor frame')
assert(sprite.width == 16 and sprite.height == 16, 'Expected 16px cursor')
print('Resizing cursor to 32px')
sprite:resize(32, 32)
print('Saving derived sprite')
sprite:saveAs(app.params.output)
sprite:close()
print('Cursor scale complete')
app.exit()
