import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { siteConfig } from '../src/config/site.js';
import { createDesktopRouteCatalog } from '../src/routing/catalog.js';
import { listFiles } from '../contracts/novel-release-v2/validate.mjs';
import { receivedProjects } from '../src/shared/novel/model.js';
import { validateReleases } from './lib/releases.mjs';
import { assertOwnedDirectory, writeFile } from './lib/files.mjs';
export const projectRoot = fileURLToPath(new URL('../', import.meta.url));

export async function build() {
  const projects = JSON.parse(await fs.readFile(path.join(projectRoot, 'catalog/projects.json'), 'utf8'));
  const releases = await validateReleases(projectRoot, projects);
  const runtimeProjects = receivedProjects(projects, releases);
  const catalog = createDesktopRouteCatalog({ ...siteConfig, works: runtimeProjects });
  const sourceFiles = await listFiles(path.join(projectRoot, 'src'));
  const assetFiles = await listFiles(path.join(projectRoot, 'assets'));
  const output = await assertOwnedDirectory(projectRoot, 'dist');
  const stage = await assertOwnedDirectory(projectRoot, '.dist-build');
  await fs.rm(stage, { recursive: true, force: true });
  await fs.mkdir(stage);
  try {
    for (const file of sourceFiles) if (file !== 'index.html') await writeFile(stage, `app/${file}`, await fs.readFile(path.join(projectRoot, 'src', file)));
    for (const file of assetFiles) await writeFile(stage, `assets/${file}`, await fs.readFile(path.join(projectRoot, 'assets', file)));
    await writeFile(stage, 'app/shared/novel/markdown-profile.js', await fs.readFile(path.join(projectRoot, 'contracts/novel-release-v2/markdown.mjs')));
    await writeFile(stage, 'catalog/projects.json', JSON.stringify(runtimeProjects, null, 2) + '\n');
    for (const release of releases) for (const file of release.files) {
      const bytes = await fs.readFile(path.join(projectRoot, release.project.release, file.path));
      if (createHash('sha256').update(bytes).digest('hex') !== file.sha256) throw new Error(`Release changed while building: ${file.path}`);
      await writeFile(stage, release.project.release + file.path, bytes);
    }
    const shell = await fs.readFile(path.join(projectRoot, 'src/index.html'), 'utf8');
    for (const route of ['', ...catalog.byPath.keys()]) {
      const base = route ? '../'.repeat(route.split('/').filter(Boolean).length) : './';
      const html = shell.replace('<head>', `<head>\n  <!-- Generated by scripts/build.mjs; edit src/index.html. -->\n  <base href="${base}">`);
      await writeFile(stage, route + 'index.html', html);
    }
    await writeFile(stage, '.nojekyll', '');
    await writeFile(stage, 'release-integrity.json', JSON.stringify(releases.map(({ project, manifest, ...record }) => ({ id: project.id, contract: `${manifest.kind}-v${manifest.schemaVersion}`, ...record })), null, 2) + '\n');
    // Check local references after assembling the actual output, before replacing dist.
    for (const file of sourceFiles.filter(file => file.endsWith('.js'))) {
      const code = await fs.readFile(path.join(stage, 'app', file), 'utf8');
      for (const match of code.matchAll(/(?:from\s*|import\s*)['"](\.[^'"]+)['"]/g)) {
        const target = path.resolve(stage, 'app', path.dirname(file), match[1]);
        if (!target.startsWith(stage + path.sep)) throw new Error('Module import escapes output');
        await fs.access(target);
      }
    }
    for (const match of shell.matchAll(/(?:href|src)="((?:assets|app)\/[^"#]+)"/g)) await fs.access(path.join(stage, match[1]));
    for (const file of sourceFiles.filter(file => file.endsWith('.css'))) {
      const css = await fs.readFile(path.join(stage, 'app', file), 'utf8');
      for (const match of css.matchAll(/url\(["']?([^"')]+)["']?\)/g)) {
        if (/^(data:|https?:|#)/.test(match[1])) continue;
        const target = path.resolve(stage, 'app', path.dirname(file), match[1]);
        if (!target.startsWith(stage + path.sep)) throw new Error('CSS asset escapes output');
        await fs.access(target);
      }
    }
    await fs.rm(output, { recursive: true, force: true });
    await fs.rename(stage, output);
    console.log(`Built dist: ${catalog.byPath.size + 1} desktop pages, ${releases.length} received releases.`);
    return { routes: ['', ...catalog.byPath.keys()], releases: releases.map(item => ({ id: item.project.id, digest: item.digest })) };
  } catch (error) { await fs.rm(stage, { recursive: true, force: true }); throw error; }
}
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  build().catch(error => { console.error(error); process.exitCode = 1; });
}
