param([switch]$Check)
$ErrorActionPreference = 'Stop'
$projectRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$tree = Get-Content -LiteralPath (Join-Path $projectRoot 'project-task-tree.json') -Raw | ConvertFrom-Json
$events = @(Get-Content -LiteralPath (Join-Path $projectRoot $tree.metadata.eventLogPath) | Where-Object { $_.Trim() } | ForEach-Object { $_ | ConvertFrom-Json })
$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('# Task Tree')
$lines.Add('')
$lines.Add('Generated by `scripts/generate-task-tree-doc.ps1`. DO NOT EDIT MANUALLY. 不得手工编辑。')
$lines.Add('')
$lines.Add("Project: $($tree.projectName)")
$lines.Add('')
$lines.Add("Status: $($tree.status); current context: $($tree.currentContextTaskId); delivery: $($tree.metadata.deliveryState).")
$lines.Add('')
$lines.Add('| Task | Parent | Status | Return point |')
$lines.Add('| --- | --- | --- | --- |')
foreach ($task in $tree.tasks) {
    $parentName = if ($null -eq $task.parent) { 'root' } else { ($tree.tasks | Where-Object id -eq $task.parent).name }
    $lines.Add("| $($task.name) | $parentName | $($task.status) | $($task.returnPoint) |")
}
$lines.Add('')
$lines.Add('## Transitions')
$lines.Add('')
foreach ($event in $events) { $lines.Add("- $($event.date) / $($event.event) / $($event.taskId) / $($event.status): $($event.detail)") }
$output = ($lines -join "`n") + "`n"
$target = Join-Path $projectRoot $tree.metadata.generatedViewPath
if ($Check) {
    if (-not (Test-Path -LiteralPath $target -PathType Leaf) -or [System.IO.File]::ReadAllText($target) -cne $output) { throw 'Generated task view is missing or out of date.' }
    Write-Output 'Generated task view is current.'
} else {
    [void][System.IO.Directory]::CreateDirectory([System.IO.Path]::GetDirectoryName($target))
    [System.IO.File]::WriteAllText($target, $output, [System.Text.UTF8Encoding]::new($false))
    Write-Output 'Generated docs/TASK_TREE.md.'
}
